#!/usr/bin/env bash
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot1_1" --delta 0.1&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot1_2" --delta 0.1&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot1_3" --delta 0.1&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot1_4" --delta 0.1&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot1_5" --delta 0.1&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot1_6" --delta 0.1&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot05_1" --delta 0.05&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot05_2" --delta 0.05&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot05_3" --delta 0.05&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot05_4" --delta 0.05&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot05_5" --delta 0.05&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot05_6" --delta 0.05&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot01_1" --delta 0.01&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot01_2" --delta 0.01&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot01_3" --delta 0.01&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot01_4" --delta 0.01&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot01_1" --delta 0.01&
python pdg_learn.py --name "pdg_one_var_stepsize_del_0dot01_6" --delta 0.01&
